### ISSUE TITLE
Bonsai closes when losing lock of NP1.0e during acquisition when BNO is isntantiated

### ISSUE THREAD

**Issue by cjsha** [neurogears/onix-refactor#121]
While acquisition is active including a np1.0e headstage, if the headstage loses lock, Bonsai crashes and closes with no message.
This has been reproduced on a demo machine running the library outside Visual Studio, so there might be an uncaught exception that maybe running through VS gets caught.

This only happens when the BNO node is instantiated and does not happen when it is not present or with hs64, so it is probably related with the i2c functions used to poll the BNO.

**Comment by aacuevas** [comment]
I was the one who actually filled the report, we were at FENS and it was something that happened from time to time.

Simplest workflow is create context -> Configure NP1.0e headstage -> start
Neuropixels1.0eBnoData -> Quaternion

Just run it and close the switch to force a lock loss (or rather, a disconnect)

In release mode, at least, this causes the whole bonsai to close silently instead of data just stopping or the workflow failing with an error. 

Similar tests with other headstages that do not perform i2c polling just result in streams from these hs being halted (which makes sense), so the most likely suspect is an unhandled exception on i2c failure
